name: CD
on: 
  release:
    types: published
jobs:
  deploy:
    name: deploy on vercel
    runs-on: ubuntu-latest

    if: ${{github.event.workflow_run.conclusion == 'success'}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-versios: 22
          
      - name: insall dependenceis
        run: npm install

      - name: Start JSON Server
        run: npm run server &

      - name: Wait for JSON Server
        run: npx wait-on http://localhost:4000

        
       # Step 4: Install the Vercel CLI globally
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Step 5: Pull Vercel Environment Information
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_KEY }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          
      # Step 6: Build Project Artifacts
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_KEY }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      # Step 7: Deploy Project Artifacts to Vercel
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_KEY }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          
